# Generated by Django 5.1.6 on 2025-06-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Corrieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corriere', models.CharField(max_length=50, unique=True)),
                ('indirizzo_corriere', models.CharField(default='Via Tirino', max_length=255)),
                ('capacita_massima', models.IntegerField(default=0)),
                ('area_di_copertura_geografica', models.CharField(max_length=50)),
                ('codice_corriere', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Corriere',
                'verbose_name_plural': 'Corrieri',
            },
        ),
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_mezzo', models.CharField(max_length=50, unique=True)),
                ('targa', models.CharField(max_length=50)),
                ('capacita_massima_peso', models.IntegerField(null=True)),
                ('capacita_massima_volume', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Mezzo',
                'verbose_name_plural': 'Mezzi',
            },
        ),
        migrations.CreateModel(
            name='Stato_Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_stato', models.CharField(default='STATO', max_length=10)),
                ('stato_attuale', models.CharField(choices=[('Assegnato', 'Assegnato'), ('Transito', 'Transito'), ('In Consegna', 'In Consegna'), ('Completato', 'Completato')], default='Assegnato', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ordini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordine', models.CharField(max_length=50, unique=True)),
                ('indirizzo_di_consegna', models.CharField(max_length=50)),
                ('data_e_ora_stimata_di_consegna_richiesta', models.CharField(max_length=50)),
                ('priorità', models.CharField(choices=[('Alta', 'Priorità Alta'), ('Media', 'Priorità Media'), ('Bassa', 'Priorità Bassa')], max_length=10)),
                ('stato_ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.stato_ordine')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
